//import './iplteam.css'

const iplTeams = [
  {
    id: 1,
    name: "Chennai Super Kings",
    abbreviation: "CSK",
    city: "Chennai",
    captain: "Ruturaj Gaikwad",
    className: "csk",
  },
  {
    id: 2,
    name: "Delhi Capitals",
    abbreviation: "DC",
    city: "Delhi",
    captain: "Rishab Pant",
    className: "dc",
  },
  {
    id: 3,
    name: "Kings XI Punjab",
    abbreviation: "KXIP",
    city: "Mohali",
    captain: "Shikhar Dhawan",
    className: "kxip",
  },
  {
    id: 4,
    name: "Kolkata Knight Riders",
    abbreviation: "KKR",
    city: "Kolkata",
    captain: "Shreyas Iyer",
    className: "kkr",
  },
  {
    id: 5,
    name: "Mumbai Indians",
    abbreviation: "MI",
    city: "Mumbai",
    captain: "Hardik Pandya",
    className: "mi",
  },
  {
    id: 6,
    name: "Rajasthan Royals",
    abbreviation: "RR",
    city: "Jaipur",
    captain: "Sanju Samson",
    className: "rr",
  },
  {
    id: 7,
    name: "Royal Challengers Bangalore",
    abbreviation: "RCB",
    city: "Bangalore",
    captain: "Fap Duplessi",
    className: "rcb",
  },
  {
    id: 8,
    name: "Sunrisers Hyderabad",
    abbreviation: "SRH",
    city: "Hyderabad",
    captain: "Pat cummins",
    className: "srh",
  },
  {
    id: 9,
    name: "Gujarat Titans",
    abbreviation: "GT",
    city: "Gujarat",
    captain: "Shubman Gill",
    className: "gt",
  },
  {
    id: 10,
    name: "Lucknow Super Gaints",
    abbreviation: "LSG",
    city: "Lucknow",
    captain: "KL Rahul",
    className: "lsg",
  },
];

export default iplTeams;
